ajouter_etab:
    path:     /profile/etablissement/ajouter
    defaults: { _controller: ProfilBundle:Etablissement:ajouter }
list_etab:
    path:     /etablissement/list
    defaults: { _controller: ProfilBundle:Etablissement:listAll }
alljson_etab:
    path:     /etablissement/alljson
    defaults: { _controller: ProfilBundle:Etablissement:alljson }
best_etab:
    path:     /
    defaults: { _controller: ProfilBundle:Etablissement:list }
supprimer_etab:
    path:     /etablissement/supprimer/{idDelete}
    defaults: { _controller: ProfilBundle:Etablissement:supprimer }
modifier_etab:
    path:     /etablissement/modifier/{idUpdate}
    defaults: { _controller: ProfilBundle:Etablissement:modifier }


ajouter_photo:
    path:     /photo/ajouter
    defaults: { _controller: ProfilBundle:Photo:ajouter }

supprimer_photo:
    path:     /photo/supprimer
    defaults: { _controller: ProfilBundle:Photo:supprimer }

list_photo:
    path:     /photo/list
    defaults: { _controller: ProfilBundle:Photo:list }

modifier_photo:
    path:     photo/modifier
    defaults: { _controller: ProfilBundle:Photo:modifier }

ajouter_utilisateur:
    path:     /utilisateur/ajouter
    defaults: { _controller: ProfilBundle:Utilisateur:ajouter }

supprimer_utilisateur:
    path:     /utilisateur/supprimer/{idDelete}
    defaults: { _controller: ProfilBundle:Utilisateur:supprimer }

modifier_utilisateur:
    path:     /utilisateur/modifier/{idUpdate}
    defaults: { _controller: ProfilBundle:Utilisateur:modifier }

list_utilisateur:
    path:     /utilisateur/list
    defaults: { _controller: ProfilBundle:Utilisateur:list }

all_Json_utilisateur:
    path:     /utilisateur/alljson
    defaults: { _controller: ProfilBundle:Utilisateur:all }
